[package]
name = "walk-the-dog"
version = "0.1.0"
edition = "2024"

[dependencies]
browser-panic-hook = "0.2.0"
wasm-bindgen = "0.2.108"
web-sys = { version = "0.3.85", features = ["Window", "Document", "HtmlElement", "Text", "console"] }
