[package]
name = "walk-the-dog"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.108"
web-sys = { version = "0.3.85", features = ["Window", "Document", "HtmlElement", "Text"] }
